# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Dynamii Lab
email: acesolo@gmail.com
description: 杜罗华童鞋的个人网站.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://dynamii.org" # the base hostname & protocol for your site
twitter_username: trowa
github_username:  itrowa

# Build settings
markdown: kramdown

permalink: /:year/:month/:day/:title 
atom_path: /atom.xml

# ----------------------------------------
# custom variables
# ----------------------------------------

# my custom header nav menu
head_menu:
    - name:             Home
      url:              /
    - name:             Archives
      url:              /archive/
    - name:             About
      url:              /about/

# 导航栏的下拉菜单
# 可以为一个项目设置role = seperator|header, 表示它们是分隔符|下拉菜单的Header标题
head_dp_menu:
    - name:             Places
      items:
        - name:         新浪围脖
          url:          http://weibo.com/itrowa/
        - name:         Steam
          url:          http://steamcommunity.com/profiles/76561198081721002/
        - name:         Flickr
          url:          http://www.flickr.com/photos/trowa_barton
        - name:         -------------
          role:         seperator
        - name:         collection
          role:         header
        - name:         "Design & Illustration & Analysis"
          url:          https://www.zhihu.com/collection/36644506
        - name:         x-plane资源综合索引
          url:          http://dynamii.org/2013/01/29/x-plane-index

# 导航栏右方的项目.
head_right_menu:
    - name:         Feed
      url:          /feed.xml

# disqus setting:
disqus_short_name: dynamii

# google analytics
ga_tracking_id: 'UA-31173648-1'

# footer info
footer_info: > 
    采用<a href="http://creativecommons.org/licenses/by-nc-sa/3.0/" title="by-cc-sa 3.0" target="_blank">
    署名-非商业性使用-相同方式共享协议</a>发布. 
    <a href="http://dynamii.org/about" title="about dynamii lab">DYNAMII.ORG</a> Since 2006 - 2016 
    is powered by <a href="http://pages.github.com/" target="_blank">Github</a>.